### PR TITLE
57 dockerize example tool

### PR DESCRIPTION
**Pull request by Ivan-E-Johnson**
# Overview
Add the Ability to dockerize our Example tool and process data via the dockerized Image

# Implementation
created Docker file

# Testing
Manual Testing 

# Problems Faced
I was trying to make it too complex at first and that cause me to not make progress. Once I simplified it became much easier. I also ran into problems with the base level package requirements

### CODE REVIEW

**Review by mbrzus — APPROVED** [review]
good work!

**Comment by powersaudrey25** [comment]
is this still 11 gb or were you able to make it smaller?

**Comment by mbrzus** [comment]
@powersaudrey25 I started working on it but do not have it completed yet. I will need to test it to ensure it is working correctly and play with the requirements. I hope to have that completed by the end of today

**Comment by zmorris248** [comment]
Sounds good, I think this looks great

**Pull request merged**
