### PR TITLE
129 decrease size of braintool docker image

### LINKED ISSUE #129: Decrease Size of BrainTool Docker Image
**If this feature request related to a problem? Please describe.**
Currently we have a docker image is ~11 GiB. We dont wan't to deploy something this large and want to decrease the size for development time. 

**Rationale**
Will help development team and allow us to deploy without breaking the bank

**Implementation Ideas**
Most of the size is from ITK and Torch so we will need to find what we need out of those packages and only install those sections 
**Additional Context**

### PR DESCRIPTION
**Pull request by mbrzus**
# Overview
This pull requests creates "light" version of the example tool to reduce the environment dependencies from 6.7 GB to 849 MB.

Currently, the tool still performs the DICOM data checking and sanitization but produces empty report. However, it still encodes the report to the DICOM format thus maintaining the full functionality from data types and delivery items.

This changed required restructurization of the repo by moving the example data to the base level to avoid duplicating it.
 
# Implementation
- removed the functionality related to the actual image processing which allowed for removal of large AI related dependencies.
- create docker related files for the light version of the example tool
- move data to base level

# Testing
Testing should be performed the same way as the example_tool

Closes #129

### CODE REVIEW

**Comment by mbrzus** [comment]
> ## [Quality Gate Failed](https://sonarcloud.io/dashboard?id=uiowaSEP2024_002_ImagePro&pullRequest=132) **Quality Gate failed**
> 
> Failed conditions  [45.0% Duplication on New Code](https://sonarcloud.io/component_measures?id=uiowaSEP2024_002_ImagePro&pullRequest=132&metric=new_duplicated_lines_density&view=list) (required ≤ 3%)
> 
> [See analysis details on SonarCloud](https://sonarcloud.io/dashboard?id=uiowaSEP2024_002_ImagePro&pullRequest=132)

@Ivan-E-Johnson @zmorris248 @powersaudrey25 the new example_tool_light is a copy of example_tool with limited functionality. For the purpose of easy switching between the two (which will be important especially in the AWS deployment) I propose to ignore the SonarCloud error

**Review by Ivan-E-Johnson — APPROVED** [review]
Looks good!

**Comment by Ivan-E-Johnson** [comment]
@mbrzus @zmorris248 I dont see a way on sonar cloud to disable the check so we may need to do this on github. Do you want me to disable the rule on github merge and then reenable it?

**Comment by zmorris248** [comment]
@Ivan-E-Johnson I think that is the best way to go about this since it is a unique situation.

**Review by zmorris248 — APPROVED** [review]

**Comment by powersaudrey25** [comment]
I created a new quality gate on sonarcloud that doesn't check for duplication I am go to try and run this pr with it now

**Comment by powersaudrey25** [comment]
> I created a new quality gate on sonarcloud that doesn't check for duplication I am go to try and run this pr with it now

we can switch back to our other quality gate whenever we want

**Comment by zmorris248** [comment]
@mbrzus  When I build the exampletool light docker and run the script to run it, I get the following error: 
docker: Error response from daemon: pull access denied for brainmasktool, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.

Do you know what this could be?

**Comment by mbrzus** [comment]
> @mbrzus When I build the exampletool light docker and run the script to run it, I get the following error: docker: Error response from daemon: pull access denied for brainmasktool, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
> 
> Do you know what this could be?

I will need more info. do you run the docker only or are you running it from within the Orthanc Receiver Agent?

**Pull request merged**
