### PR TITLE
114 update job configurations to study configurations

### PR DESCRIPTION
**Pull request by powersaudrey25**
# Overview

!!!! Waiting to merge until bug is fixed in main

This pull request merges our work on refactoring the job_monitoring_application to refer to 'study_configuration' instead of 'job_configuration'. It includes a renaming of all references to a 'job_configuration' to a 'study_configuration' in the frontend, backend, trackerapi, and internal_servers.

The following migrations were created:
- creation of the study_configuration table
- addition of the study_configuration_id column to the study table
- addition of the study_configuration_id column to the step_configuration table
- deletion of job_configs table
- deletion of job_config column from study table
- deletion of job_config column from step table
- move data from job_config table to study_config table

These refactorings make our app more coherent and are more in line with real world medical imaging applications.
# Implementation

Migrations to the database
Refactoring in frontend, backend, trackerapi, and internal_servers

# Testing

All tests related to job_config were changed to reference study_config. 
All tests in backend, trackerapi, and frontend pass.
All Cypress tests pass.

# Problems Faced

I had accidentally changed a step configuration reference to a study config reference which broke a lot of tests. After fixing that though no other significant problems since I followed the procedure outlined in PR 113

# Notes

No visible frontend changes.

### CODE REVIEW

**Review by mbrzus — APPROVED** [review]

**Comment by powersaudrey25** [comment]
@mbrzus Michal I know you were running into some problems with the agent/logger, was that related to this PR or is this fine to merge? @zmorris248 were you able to run the agent/logger and create a job with this PR?

**Comment by mbrzus** [comment]
> @mbrzus Michal I know you were running into some problems with the agent/logger, was that related to this PR or is this fine to merge? @zmorris248 were you able to run the agent/logger and create a job with this PR?

Yes, I was getting issues on this branch, I described them on teams (conversation on March 8th).

**Comment by zmorris248** [comment]
@powersaudrey25 When I ran it with you on the last day before break, I did see some information on the Orthancs already, related to @mbrzus's first issue on teams. This didn't affect me running the system though or the agent. I could see things getting updated on the front end. I would get an error on step 4, as I think everyone else is. I believe it would keep re-running the study because step 4 was never marked as completed, so our system finishes the process and still finds a study in queue and restarts the process.

**Comment by powersaudrey25** [comment]
@mbrzus @zmorris248 thanks! just wanted to get the problems documented on this branch/pr

**Pull request merged**
