### PR TITLE
#27 merge .githubs

### PR DESCRIPTION
**Pull request by zmorris248**
# Overview
We are integrating the old repo's .github folder into our own.

# Implementation
I have moved all of the workflow files from the job-monitoring-app to our root .github folder in a new workflows folder.
I have deleted the non-root .github folder in job-monitoring-app

### CODE REVIEW

**Comment by Ivan-E-Johnson** [comment]
Do we know why the CI tests are failing/ can they be fixed? @zmorris248 

@mbrzus we need to update the ruleset so that PR's failing CI cannot be merged into main.

**Comment by powersaudrey25** [comment]
> Do we know why the CI tests are failing/ can they be fixed? @zmorris248
> 
> @mbrzus we need to update the ruleset so that PR's failing CI cannot be merged into main.

@Ivan-E-Johnson @zmorris248  looks like some jobs are failing because files can't be found on certain paths should be easy fixes hopefully

**Comment by powersaudrey25** [comment]
@Ivan-E-Johnson  @zmorris248 I think I have pushed fixes for correcting the file paths however now 3/4 errors we get might be due to permissions? I am not sure

The error in the frontend CI execute lint happens with the setup-node action and is identical to the one discussed in https://github.com/actions/setup-node/issues/624 I attempted what they outlined but didn't have any luck. Can someone else try?

**Comment by Ivan-E-Johnson** [comment]
@powersaudrey25 sounds good, thank you for investigating further. I think we need to comment the invalid CI/workflow sections out. IE revert the workflow to a state where CI passed on valid changes and fails on invalid. We shouldn't fail on valid changes due to incomplete setup.

**Comment by mbrzus** [comment]
As for the rulesets. I disabled the ruleset for the main branch due to allow the merge of the repos. As this is already completed, I will enable the ruleset back on work on modifying it to include the requirement to pass the github action.

If I understand correctly, the CI workflow are for the automated AWS deployment, correct? @Ivan-E-Johnson:
1. Could it be that they failed as the connection to our AWS instance is not working?
2. Could the deployment be the potential reason for the AWS charges we saw yesterday?

**Comment by zmorris248** [comment]
I have been looking into the failing tests, I believe that the backend, trackerapi, and cdk infra fails may be due to permissions. I am not sure, but it looks like the tests are trying to modify the coverage.xml file in those folders with a comment after running the tests, but we do not currently give github actions permission to modify files in our repo. Changing this might resolve these issues. If we keep encountering issues, i agree with @Ivan-E-Johnson 's approach.

**Comment by powersaudrey25** [comment]
I upgraded the node version and downgraded a dependency for the frontend and now the frontend ci fully passes. All that is left to fix are those permissions for backend, cdk, trackerapi.

**Comment by Ivan-E-Johnson** [comment]
@mbrzus can you review this and approve before merging?

**Comment by mbrzus** [comment]
The previous Pull Request changed the requirements file path in the dockerfile. This is a potential cause for the checks to fail.

There was also a .gitignore conflict, bt this was resolved and I do not anticipate that to be causing the failures.

**Review by mbrzus — APPROVED** [review]
All checks pass. Code changes looks good.

**Pull request merged**
